version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.13
    commands:
      - echo "Installing gomason"
      - go get github.com/nikogura/gomason
      - echo "Installing dbt"
      - bash -c "$(curl http://artifacts.lo/artifactory/dbt/install_dbt_aws.sh)"
    finally:
      - echo "Prereqs Installed"
  build:
    commands:
      - "publishing"
      - echo "Build Successful!"